#spring.application.name=security
spring:
  application:
    name: security
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
server:
  port: 8190
  servlet:
    context-path: /security
